"""LangChain tool example for one Skills instance.

Usage:
    python langchain_example/model.py

Optional dependencies:
    pip install langchain-core pydantic
"""

from __future__ import annotations

import json
from typing import Sequence
from magicskills.core.registry import ALL_SKILLS
from magicskills.core.skills import Skills

# 选中的 skill（有重名时要传 path）
s1 = ALL_SKILLS.get_skill("pdf")
s2 = ALL_SKILLS.get_skill("c_2_ast",path="/root/.agent/skills/c_2_ast")

selected = [s1, s2]
paths = sorted({s.base_dir for s in selected}, key=lambda p: p.as_posix())
my_skills = Skills(name="Askills", skills=selected, paths=paths)


# 第一种方式
import json
from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

class SkillInput(BaseModel):
    action: str = Field(...)
    arg: str = Field("")

def skill_tool_fn(action: str, arg: str = "") -> str:
    result = my_skills.skill_tool(action, arg)
    return json.dumps(result, ensure_ascii=False)

skill_tool1 = StructuredTool.from_function(
    func=my_skills.skill_tool, #skill_tool_fn,
    name="skill_tool",
    description=my_skills.tool_description,  # 直接用这里
    args_schema=SkillInput,
)

#第二种方式
from langchain_core.tools import tool

@tool("_skill_tool", description=my_skills.tool_description)
def _skill_tool(action: str, arg: str = "") -> str:
    return json.dumps(my_skills.skill_tool(action, arg), ensure_ascii=False)




from langchain_core.callbacks import BaseCallbackHandler
import json

class DebugLLMStart(BaseCallbackHandler):
    def on_chat_model_start(self, serialized, messages, **kwargs):
        print("\n" + "="*80)
        print("on_chat_model_start")
        print("kwargs keys:", list(kwargs.keys()))
        # 打印 messages
        for turn in messages:
            for m in turn:
                print(f"[{m.type}] {m.content[:300]}")
        # 尝试打印可能的工具字段
        for k in ("tools", "functions", "tool_choice", "function_call"):
            if k in kwargs and kwargs[k] is not None:
                print(f"\n[{k}]")
                try:
                    print(json.dumps(kwargs[k], ensure_ascii=False, indent=2))
                except Exception:
                    print(kwargs[k])
        # serialized 里也可能有
        print("\nserialized keys:", list(serialized.keys()))
        print("serialized:", serialized)
        print("="*80)



# 调用模型
from langgraph.prebuilt import create_react_agent
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
import os 
load_dotenv()

# 选一个工具（推荐 StructuredTool）
tools = [skill_tool1]  # 或 [_skill_tool]

llm = ChatOpenAI(
    model=os.getenv("OPENAI_MODEL"),
    temperature=0.0,
    base_url=os.getenv("OPENAI_BASE_URL"),   # 没有就会是 None
    api_key=os.getenv("OPENAI_API_KEY"),
    callbacks=[DebugLLMStart()], 
)
  
agent = create_react_agent(llm, tools)

from langchain_core.messages import AIMessage, ToolMessage

result = agent.invoke({
    "messages": [(
        "user", "我想将 #include <stdio.h>\n\nint main() {\n    puts(\"Generated by agent\");\n    return 0;\n}\n  这段代码转换为ast"#"我想非常深入的了解ast" #"我想将 #include <stdio.h>\n\nint main() {\n    puts(\"Generated by agent\");\n    return 0;\n}\n  这段代码转换为ast"
                  )]
})


# 保存信息
for i, m in enumerate(result["messages"]):
    msg_type = getattr(m, "type", m.__class__.__name__)
    print(f"\n--- {i} | {msg_type} ---")

    # 内容
    if getattr(m, "content", None):
        print(m.content)

    # 模型发起的工具调用
    if isinstance(m, AIMessage) and getattr(m, "tool_calls", None):
        print("\n[tool_calls]")
        for tc in m.tool_calls:
            print(tc)

    # 工具返回
    if isinstance(m, ToolMessage):
        print("\n[tool_result]")
        print(m.content)

print("\n=== final ===")
print(result["messages"][-1].content)


