from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool
from langchain_core.prompts import ChatPromptTemplate
from langchain.agents import create_structured_chat_agent, AgentExecutor
from langchain_community.chat_models import ChatTongyi
from dotenv import load_dotenv
from langchain.agents import create_tool_calling_agent, AgentExecutor

from typing import Dict, Any

# =========================================================
# 1. 修正 PYTHONPATH
# =========================================================

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from skills_for_all_agent.skill_tool import skill_tool,DEFAULT_SKILLS_ROOT

load_dotenv()

# =========================================================
# 2. Tool 输入 schema（action + arg）
# =========================================================

class SkillToolInput(BaseModel):
    payload: Dict[str, Any] = Field(
        ...,
        description=(
            "A dict with the following format:\n"
            "{\n"
            '  "action": "<action_name>",\n'
            '  "arg": "<string argument>"\n'
            "}"
        )
    )

# =========================================================
# 3. Tool 执行封装
# =========================================================

def _run_skill_tool(payload: Dict[str, Any]) -> str:
    result = skill_tool(payload)
    return json.dumps(result, ensure_ascii=False, indent=2)


# =========================================================
# 4. 构建 StructuredTool
# =========================================================

def build_skill_tool() -> StructuredTool:
    return StructuredTool.from_function(
        name="skill_tool",
        description=(
              f"""
    Unified skill tool. If you are not sure, you can first use the "list_metadata" function of this tool to search for available skills. Then, determine which skill might be the most useful. After that, try to read the SKILL.md file under this skill path to get more detailed information. Finally, based on the content of this file, decide whether to read the documentation in other paths or directly execute the relevant script.

    Input format:
        {{
            "action": "<action_name>",
            "arg": "<string argument>"
        }}

    Actions:
    - list_metadata: arg = skills root directory (default: {DEFAULT_SKILLS_ROOT})
    - read_file:     arg = file path
    - run_command:   arg = full command string
    """
        ),
        func=_run_skill_tool,
        args_schema=SkillToolInput,
    )

# =========================================================
# 5. 主程序（StructuredChatAgent）
# =========================================================
def main():
    print(DEFAULT_SKILLS_ROOT)
    tool = build_skill_tool()

    llm = ChatTongyi(
        model_name="qwen3-max-preview",
        api_key="sk-8c8fba3079574742a4ee85dce972d409",
        temperature=0,
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a helpful assistant. Use tools when needed."),
        ("human", "{input}"),
        ("assistant", "{agent_scratchpad}"),
    ])

    agent = create_tool_calling_agent(
        llm=llm,
        tools=[tool],
        prompt=prompt,
    )

    agent_executor = AgentExecutor(
        agent=agent,
        tools=[tool],
        verbose=True,
        max_iterations=10,
    )

    result = agent_executor.invoke({
        "input":"" #"我想非常深入的了解ast" #"我想将 #include <stdio.h>\n\nint main() {\n    puts(\"Generated by agent\");\n    return 0;\n}\n  这段代码转换为ast"
    })

    print("\n===== FINAL OUTPUT =====")
    print(result["output"])


if __name__ == "__main__":
    main()
